all: attacker-victim.c attacker-victim_unrolled_600_700.c attacker-victim_unrolled_999_980.c
	gcc attacker-victim.c -o exec
	gcc attacker-victim_unrolled_600_700.c -o exec_unrolled_600_700
	gcc attacker-victim_unrolled_999_980.c -o exec_unrolled_999_980
